### ISSUE TITLE
question: setTemplate doesn't know env function

### ISSUE THREAD

**Issue by dennybaa** [roboll/helmfile#1004]
Hello @mumoshu,

I've been playing around with relatively new features and bumped into that that during the second pass I get this failure, is this expected behavior?

```
second-pass rendering result of "80-identity.yaml.part.0":
11:     setTemplate:   
12:     - name: config.logging\.json.logLevel
13:       value: "{{ env "LOG_LEVEL"  }}"

err: failed to read 80-identity.yaml: reading document at index 1: yaml: line 13: did not find expected key
```

I've checked other functions like upper and default they do work. Could you please shortly explain why this is so or maybe it's a bug?

**Comment by mumoshu** [comment]
@dennybaa Sorry I'm overwhelmed by the sea of github notifications. This seems like due to some mistake in your helmfile template. The second-pass rendering result should be a valid YAML, where `value: "{{ env "LOG_LEVEL"  }}"` in your result isn't a valid YAML snippet. Perhaps there was something wrong in go template comments that resulted in rendering `value: "{{ env "LOG_LEVEL"  }}"`.

**Comment by dennybaa** [comment]
@mumoshu No worries and thank you. I totally understand, that's why I closed the issue since it was definitely an error...
