### ISSUE TITLE
Better debugging/error output when using `exec` filter

### ISSUE THREAD

**Issue by ggillies** [roboll/helmfile#1158]
Currently when you have a templating error due to something being invoked by `exec`, the error message you get back contains the command that was run and the return code of the command, but doesn't give you much more information than that to help debug.

It would be really good if upon exec failure (e.g. non-zero exit code), the error message that comes back also contains the `stout` and `stderr` text from the command that was run, in order to assist debugging.

Alternatively/additionally, it would be good when running helmfile with `--log-level debug` to instead display a log message showing `exec` commands being run, along with their `stdout` and `stderr`.

**Comment by mumoshu** [comment]
@ggillies Thanks! The error reporting is updated via #1159. Could you try the latest Helmfile release and confirm if you like it?

---

I have been considering `exec` to be the last resort that people shouldn't use usually and hence I didn't put much love to, that's why the error message isn't friendly at all.

But after almost a year or two spending time supporting people using Helmfile, it turns out that, in practice, `exec` is used widely, we can't simply avoid it. I'm giving up suggesting to avoid it and instead trying to make it a bit more usable now :)

**Comment by ggillies** [comment]
@mumoshu thanks so much for turning this around so quickly! What you have is perfect for us! Thanks again!
