### ISSUE TITLE
"helmfile diff" does not see "installed: false" as a difference in helmfile 0.104.0

### ISSUE THREAD

**Issue by dabelenda** [roboll/helmfile#1237]
When you create a release in helmfile, then decide to uninstall it by putting "installed: false" in the release bloc, helmfile apply does nothing because helmfile diff does not see any differences.

This makes it tricky to understand what exactly helmfile will do before forcing a "helmfile sync".

**Comment by mumoshu** [comment]
Since #1186 and Helmfile v0.109.0 it should detect to-be-deleted releases with output like:

```
Affected releases are:
  raw (incubator/raw) DELETED
```

Are you seeing different behaviour?

**Comment by mumoshu** [comment]
Also - helm-diff, by its nature, unable to detect deleted releases. That's why Helmfile was enhanced to show the planned deletion in the diff summary as explained above.

I.e. helm-diff showing a huge diff with every single line marked as deleted didn't make sense me. So the next possible way was to show it in the diff summary produced by Helmfile.

**Comment by dabelenda** [comment]
Oh, I will test it.
I did not see anything in the Release notes, so I assumed behaviour was not changed.

**Comment by dabelenda** [comment]
Yep sorry for the noise, it works as described.
