### ISSUE TITLE
Catch up the recent change in helm-diff

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#130]
We're seeing a confusing deprecation warning message `Command "helm diff" is deprecated, use "helm diff upgrade" instead` from helm-diff, which has troubled users like @rendhalver in e.g. #127.

As the "deprecation" implies, this is caused by the fact that helmfile is calling helm-diff by running `helm diff` but the command is deprecated in favor of `helm diff upgrade`.
We should be able to suppress that by just appending `upgrade` when calling helm-diff.

**Comment by rmartinez3** [comment]
latest helm diff made changes since diff now supports diffs by upgrade, revisions, and how a rollback would look like. For default diff appending upgrade will fix the deprecated warning. Would revision, upgrade, rollback be set as subcommand in diff command section ? I'm happy to help catch up diff command to latest helm diff. So just asking for details to start on pull request.

**Comment by mumoshu** [comment]
> For default diff appending upgrade will fix the deprecated warning

Certainly!

> Would revision, upgrade, rollback be set as subcommand in diff command section ?

Can we talk about it in a separate issue?
Sounds like an useful feature, yet I don't have a specific use-case of my own.
