### ISSUE TITLE
[feature] Add a way to track resources during upgrade

### ISSUE THREAD

**Issue by semoac** [roboll/helmfile#1320]
Hi!

I would be awesome if Helmfile implements a way to run a tracker of resources on the side while Helm is upgrading a  release.
Something https://github.com/werf/kubedog for example, so we could see the rollout and get logs from pods.

:)

**Comment by dudicoco** [comment]
I agree that this would be an amazing feature, there is a closed PR which integrates kubedog within helm: https://github.com/helm/helm/pull/3479/files

@semoac add your voice on the PR comments so maybe it will be added to helm.

**Comment by dudicoco** [comment]
I have found an incomplete workaround for adding kubedog to helmfile via hooks:
```
  hooks:
  - events: ["postsync"]
    showlogs: true
    command: "sh"
    args: ["kubedog.sh"]
```

kubedog.sh:
```
cat kubedog-config.json | kubedog multitrack
``` 

The problem is that the hook is running after the release is already installed so the output is useless.

@mumoshu can you please advise on a workaround to use this amazing feature with helmfile? Perhaps a new type of non-blocking hook that runs in a separate thread?

Thanks!

**Comment by evgkrsk** [comment]
There is better workaround (instead of postsync-hook): use werf itself instead of helm binary (export WERF_HELM3_MODE=1 with werf-1.2+ make it compatible with "helmfile -b werf").

Sure, it would be great feature if helmfile may show live output from helmBinary (no matter if it helm or werf).

**Comment by rodrigorfk** [comment]
Hi there, I thought worth mentioning here that since [v0.146.0](https://github.com/helmfile/helmfile/releases/tag/v0.146.0), helmfile now supports passing the `--enable-live-output` argument, which in combination of [Werf resource tracking](https://werf.io/documentation/v1.2/advanced/helm/deploy_process/steps.html#resource-tracking) can provide a pretty nice output progress for the deployment, please checkout [this discussion](https://github.com/helmfile/helmfile/discussions/283) where I first suggested the feature.
