### ISSUE TITLE
Do release names need to be unique?

### ISSUE THREAD

**Issue by Shadowghost** [roboll/helmfile#1339]
I have releases with the same name but in different namespaces.
Whenever I run `helmfile -f helmfile.yaml -l namespace=<namespace> sync` the process fails on processing `<releasename>` (which uses `<repo>/<chart>`) with the following error message:
```
Error: failed to download "<other-repo>/<other-chart>" (hint: running `helm repo update` may help)
```
`<other-repo>/<other-chart>` ist the helm chart used by the release `<releasename>` in another namespace.
The second release is defined after the first in the helmfile, both repos are defined in the helmfile and `verify` is set to `false` globally (because of #1176).

Anyone has an idea why this happens? I know that this was already discussed in #1213 (and fixed #1235) but it seems like it's still not properly handled.

**Comment by mumoshu** [comment]
@Shadowghost Hey!

The release names must be unique in the namespace(and kubecontext since #1390). But the error you've seen seems like due to failure in `helm fetch "<other-repo>/<other-chart>"` which should have nothing to do with the this uniqueness check done on helmfile side.

Would you mind running `helm fetch "<other-repo>/<other-chart>"` alone and see if it works?

**Comment by Shadowghost** [comment]
Fetching the chart manually works fine. As already written: It's irritating that helmfile fails with the message from above on a release in a namespace where `<other-repo>/<other-chart>` is not even used for any release in this namespace.
