### ISSUE TITLE
Feature Request: helmfile test option

### ISSUE THREAD

**Issue by Evesy** [roboll/helmfile#144]
**Feature**
An additional directive to the helmfile binary; `helmfile test`

**Why**
Helm provides `helm test` (https://github.com/kubernetes/helm/blob/master/docs/chart_tests.md) as a method to run automated tests post chart install to ensure things are working as they should be.

It would be nice to be able to run something like `helmfile test` against a particular helmfile in order to run helm tests against all charts/releases defined in the file. Either as part of the sync (i.e. `helmfile sync --test`) to be ran immediately after the corresponding chart is installed, or as a separate command ran after a sync (i.e. `helmfile test`).

A chart without tests will exit with a 0 status, so it can be safely ran against any charts.

**Comment by mumoshu** [comment]
@Evesy Thanks for the awesome feature request. I have never noticed about that helm feature. Interesting.

Can we just start by adding `helmfile test [--selector k1=v1,k2=v2,...] [--cleanup] [--timeout int] [--args ...]`?

Reasons:

For dev use-case, I prefer helmfile to do just one thing very well. In this specific case, I'd expect helmfile to just fan-out to helm, rather than doing workflow thing for me. So I'd write `helmfile sync && helmfile test` or `SELECTOR='tier=backend' bash -c 'helmfile sync -l $SELECTOR && helmfile test -l $SELECTOR` instead of introducing `helmfile sync --test`.

For production use-case, I prefer delegating anything other than just fan-out of helm commands to external workflow system like argo and brigade.
More concretely, I'd run `helmfile sync` and then `helmfile test` in separate but dependent jobs in the workflow system, so that I can benefit from reliability and durability from the system.

**Comment by Evesy** [comment]
@mumoshu `helmfile test` would probably be my preference over bringing it into the scope of `helmfile sync` for the reasons you listed above. It also gives the opportunity to run any tests on a scheduled basis without the need to kick off a helm upgrade

**Comment by Evesy** [comment]
FYI I've made a start at https://github.com/Evesy/helmfile however I've never touched any Golang before so it'll be slow progress (and a good chance I get stuck at some point!)
