### ISSUE TITLE
Ubuntu/Debian-based docker images

### ISSUE THREAD

**Issue by z0rc** [roboll/helmfile#1783]
Alpine-based docker images has their own limitations: https://dev.to/asyazwan/moving-away-from-alpine-30n4.

My personal issue: missing glibc, which leads to [inability to install aws-cli v2](https://github.com/aws/aws-cli/issues/4685) when running helmfile image in CI pipeline, and aws cli is needed when working with AWS EKS clusters. aws cli v1 works on alpine, but it isn't clear how long it will be supported.

Of course there is always an option to maintain my own docker images with tools I need, but maybe community would see value in this too.

**Comment by mumoshu** [comment]
@z0rc Hey! Thanks for bringing it up. I've no strong opinion on sticking with alpine and will happily accept contributions to add more OSes. It would be great to start by having another Dockerfile to build Ubuntu or Debian based images, so that the community can start testing.

Would you mind contributing?

**Comment by mumoshu** [comment]
#1863 for Ubuntu-based Dockerfiles(not in the release process yet. Use it as a reference to build your own)
#1956 for Debian-based images.

Closing as resolved. Thanks for your contributions @vseryozhenko and @naphta!
