### ISSUE TITLE
Add prompt or yes flag to helmfile delete

### ISSUE THREAD

**Issue by int128** [roboll/helmfile#182]
`helmfile delete` deletes all releases without any prompt. It may be dangerous because my colleague accidentally deleted all releases by the following command:

```sh
helmfile delete jenkins
```

He wanted to delete the specific release as like:

```sh
helm delete jenkins
```

I think the following behavior is nice.

1. `helmfile delete` should be error if any argument is given.
1. `helmfile delete` should show a prompt for delete confirmation, like Terraform.
1. `helmfile delete --yes` skips the prompt.

**Comment by mumoshu** [comment]
@int128 Hey! Thanks for the proposal.

I'm generally fine with the three improvements. Especially about 2 and 3, they sound like natural additions to helmfile given there's the momentum to make helmfile useful in use-cases similar to terraform.

The only thing I'd want to consider is that I and @cmeury found that `helmfile delete` would better behave similar to `helm delete` as discussed in https://github.com/roboll/helmfile/issues/71#issuecomment-376690779.

That said, how about altering your proposal to something like the below?

1. `helmfile delete foo` should fail, as the foo is redundant.
2. `helmfile destroy` should prompt before the deletion.
  - This doesn't conflict with my and @cmeury's intention to keep `helmfile delete` behave similar to `helm delete`(notice the difference between `delete` and `destroy`!
3. `helmfile destroy --yes`
  - I'd prefer `--yes` over `--force` because its short-hand `-f` is already occupied by `--file` 😉 I'm ok with `--auto-approve` if anyone wants a more terraform-like flag, but it doesn't make much sense given we already have difference between `helmfile diff` vs `terraform plan`!

WDYT?

**Comment by sstarcher** [comment]
This also brings up another point `helmfile delete jenkins` should result in a syntax error should it not?

**Comment by mumoshu** [comment]
Definitely! That would exactly be the 1. of the above suggestions, or am I missing something?

**Comment by int128** [comment]
Looks good 👍. Also the help message says `helmfile delete` accepts some arguments but it should be fixed.

```
% helmfile delete --help
NAME:
   helmfile delete - delete releases from state file (helm delete)

USAGE:
   helmfile delete [command options] [arguments...]

OPTIONS:
   --purge  purge releases i.e. free release names and histories
```

**Comment by cmeury** [comment]
Choice of CLI library is likely not a controversial issue; whatever works better works be my vote.

**Comment by sstarcher** [comment]
@mumoshu <3 cobra, but I would not be surprised if you did not have to make some breaking CLI changes to move to cobra since it handles things differently.
