### ISSUE TITLE
`gotmpl` secrets are not supported

### ISSUE THREAD

**Issue by chillum** [roboll/helmfile#1878]
unfortunately, decrypting the `.yaml.gotmpl` files doesn't work. they're not parsed as templates.

there're two independent problems here:

1. helm-secrets doesn't like JSON (not YAML) sops container (and sops defaults to JSON if the extension is not `.yaml`, but `.yaml.gotmpl`. I have a patch for this.

2. `helmfile` seems to assume that the decrypted file should be a template. not really sure what's going on, but I think it just assumes the `secrets` decrypted file is a YAML file, not a `.yaml.gotmpl`.

**Comment by mumoshu** [comment]
@chillum This should be already implemented in https://github.com/roboll/helmfile/pull/1701. I don't personally use that feature so would you mind reviewing https://github.com/roboll/helmfile/pull/1701 and see either you're misunderstanding the feature or the feature had some bug?

**Comment by jkroepke** [comment]
Hi there

in the upcoming version of helm-secrets (mention that helm plugin install will use master) the logic has been changed here.

helm-secrets will always append suffix, not only on .yaml files. Additionally, the parameter `HELM_SECRETS_DEC_SUFFIX` has been changed to `.dec`.

In context of .yaml files, it will not break helmfile since replace .yaml by .yaml.dec is the same like just append dec. But the change in helm-secret will break with files other than .yaml.

Additionally, to increase the compatibility, there is a new option for helm secret dec to just print the path of the decrypted file location. 

https://github.com/jkroepke/helm-secrets/pull/122

That should avoid some custom logic like that

https://github.com/roboll/helmfile/blob/c623730374b55949824a9522141ed27b4b8477c1/pkg/helmexec/exec.go#L276-L288

**Comment by chillum** [comment]
hm, seems to decrypt fine and it seems like I'm running into another issue.
thanks
