### ISSUE TITLE
How to pass arbitrary args to helm-diff?

### ISSUE THREAD

**Issue by evgkrsk** [roboll/helmfile#2053]
How may I pass custom args to helm-diff (via "helmfile diff" or "helmfile apply")?

There is very interesting flag "--normalize-manifests" in fresh versions of plugin, that I want to test-out...

**Comment by mumoshu** [comment]
I'm not going to add a tricky feature to let the user provide arbitrary flags to helm-diff, because it might be a big maintenance burden (for me :)

Probably a better approach would be to enhance helm-diff to be able to enable the flag via an envvar, like `HELM_DIFF_NORMALIZE_MANIFESTS=true`, so that you can run helmfile like `HELM_DIFF_NORMALIZE_MANIFESTS=true helmfile apply`.

**Comment by evgkrsk** [comment]
Okay, thanks.
