### ISSUE TITLE
0.21.0 args being reordered

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#212]
When running with `--args` the arguments are being non-deterministic rearranged.
* `helmfile sync --args "--timeout=3600 --set image.tag=blah"`

Sometimes out result is
```
exec: helm upgrade --install --reset-values blah stable/chart --version 0.1.0 --namespace=blah image.tag=blah --timeout=3600 --set
Error: flag needs an argument: --set
```

Other times
```
exec: helm upgrade --install --reset-values blah stable/chart --version 0.1.0 --namespace=blah --set image.tag=blah --timeout=3600
```

**Comment by rmartinez3** [comment]
This is caused by the getArgs function 

https://github.com/roboll/helmfile/blob/a5d42e741ba402924017ad7934943b400a705e90/main.go#L553-L570

which can be fixed  error by taking in account of string array flags 

```
        args := c.String("args")
	argsMap := map[string]string{}
	spaceflagArg := map[string]bool{}

	if len(args) > 0 {
		argsVals := strings.Split(args, " ")
		prevFlag := ""
		for _, arg := range argsVals {
			if strings.HasPrefix(arg, "--") {
				argVal := strings.SplitN(arg, "=", 2)
				if len(argVal) > 1 {
					arg := argVal[0]
					value := argVal[1]
					argsMap[arg] = value
				} else {
					argsMap[arg] = ""
				}
				prevFlag = arg
			} else {
				spaceflagArg[prevFlag] = true
				argsMap[prevFlag] = arg
			}
		}
	}
```



```
       var argArr []string

	for key, val := range argsMap {
		if val != "" {
			if spaceflagArg[key] {
				argArr = append(argArr, fmt.Sprintf("%s %s", key, val))
			} else {
				argArr = append(argArr, fmt.Sprintf("%s=%s", key, val))
			} // or

		} else {
			argArr = append(argArr, fmt.Sprintf("%s", key))
		}
	}
```

arguments will be rearranged but wont cause any errors with theses changes. Cause of this is flags are kept in a map to keep track of cli args  and helm defaults args.  So from the map the arguments are build.

I do know there is talk about changing the GetArgs function . Changes can be made in order to capture flags better and merge helm default args.

**Comment by Stono** [comment]
We've just been hit by this non-deterministic behaviour in 0.22.0 too, and have had to roll back to 0.20.0

**Comment by mumoshu** [comment]
@sstarcher @Stono Can we work around it by using `--set='image.tag=blah'`? 

@rmartinez3 your fix would work anyway! Mind sending a PR?

**Comment by sstarcher** [comment]
@mumoshu ya, a workaround is doing ensuring you always use a `=` which is what I currently have in place.

**Comment by Stono** [comment]
This manifested in another error for us, however I've head home now.  Can
recreate tomorrow.

Note: we are passing non "set" args too
