### ISSUE TITLE
Helm charts and releases: inconsistent terminology?

### ISSUE THREAD

**Issue by ilyasotkov** [roboll/helmfile#25]
Using Helm CLI shows that one Helm release can include several Helm charts - one main chart and several subcharts. Am I missing something or should `charts.yaml` therefore be `releases.yaml`?

Example: 

Generic chart: rails-app
Unique releases: dev-example-com, prod-example-com, dev-example-org, prod-example-org

Workflow:

1. Create a generic Helm chart with some default `values.yaml`
2. Add one or more releases, each with its own unique `values.yaml`

One cluster, many charts, more releases 🤔

“Helm deployment” here should be “Helm release” also. “Deployment” is a very specific Kubernetes term, and not a Helm term at all.

Am I wrong?

**Comment by xeor** [comment]
I've just found helmfile as well and was thinking the same. `charts` and `deployment` are terms that shouln't be reused in this project. At least not `charts`

**Comment by roboll** [comment]
> Using Helm CLI shows that one Helm release can include several Helm charts - one main chart and several subcharts

Yes but helm deals only in `chart`s - there is no difference between a single chart or an aggregate chart. The `charts.yml` file and `charts` section in it reference charts that helm will deploy. They may produce something you could call a release, but I'm not convinced the naming change is required.

I agree that the overlap in terminology for `deployment` isn't great - if you'd like to pr a change to the docs to call it a release I'd accept that.

**Comment by xeor** [comment]
I must admin I didn't even notice the `s` in your `charts.yml` file before you said it.. In my mind, it ended up being the same name except I knew the `helm` version used uppercase `C`.
Maybe it's because you really don't read the whole word, you just see that the file is there.. There are [a couple](http://www.boats.com/resources/beginners-guide-to-boat-terminology/) of boat terminologies that might work..? Or maybe just call it `Helmfile`?

`charts.yml` aint bad either, now that I know that the s is there :p

**Comment by gtaylor** [comment]
`charts.yml` isn't bad, but `helmfile.yml` would be slightly more obvious as to where this file came from.

**Comment by mumoshu** [comment]
@roboll First of all, thanks for sharing a great project 👍 

The OP's suggestion makes sense to me.

> The charts.yml file and charts section in it reference charts that helm will deploy. They may produce something you could call a release, but I'm not convinced the naming change is required.

Probably the description in `helm install --help` would help here.

```
$ helm install --help
This command installs a chart archive.

The install argument must be a chart reference, a path to a packaged chart,
a path to an unpacked chart directory or a URL.

*snip*

Usage:
  helm install [CHART] [flags]
```

So, `helm install` does seem to work on a "chart" at glance. But how when you add `--name` flag:

````
helm install CHART --name THE_NAME_OF_WHAT?
```

My understanding on `helm install` is `helm install $chart_name --name $release_name` to "install a chart on your cluster to create a release`. So, you're actually working on a release, rather than chart itself. Similarly, `helm delete` deletes a release but a chart.

In that sense, charts.yaml is a bit ambiguous between `charts[].name` vs `charts[].chart`:

```
charts:
   # This seems like a CHART NAME at glance, which isn't true. This is a release name
- name: brigade-project
  # What is charts[0].chart? Why isn't this chart[0].name?
  chart: brigade/brigade-project
```

IMHO this becomes more intuitive once you renamed `charts` to `releases`:

```
# List of releases managed by the helmfile command
releases:
   # The name of the release being created
- name: brigade-project
  # This is the chart to be installed on the cluster to create this release
  chart: brigade/brigade-project
```

**Comment by mumoshu** [comment]
I've submitted #35 to move this forward(maybe 😄)
