### ISSUE TITLE
apply does a sync instead of a charts

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#271]
The flow I'm seeing from apply is
* diff
* yes
* repos
* charts

If the user does not specify a version and has not ran repos recently that could cause the diff that they see to be different then what actually gets applied.

**Comment by sstarcher** [comment]
I would lean toward the latter diff, yes, charts

**Comment by mumoshu** [comment]
My guess is that basically, we should specify chart versions in helmfile.yaml. So that `helmfile apply` doesn't require you to run `hemlfile repos` beforehand, while ensuring there're no glitches between the diff and whats get applied.

In that sense, shouldn't `helmfile apply` run `repos` by default? Then how about:

`helmfile apply --skip-repo-updates`:

- diff
- yes
- deps
- charts

`helmfil apply`:

- repos
- diff
- yes
- deps
- charts

**Comment by mumoshu** [comment]
PTAL at #286! Thx.

**Comment by sstarcher** [comment]
@mumoshu, that implementation sounds good.
