### ISSUE TITLE
FR: ability to have empty helmfile

### ISSUE THREAD

**Issue by pastukhov** [roboll/helmfile#285]
Hi all!
We have two step deployments with helmfile. First is deploying helm charts ( grafana, prometheus, etc)
and second is creating namespaces with our own helm chart.
For some environments we are not creating namespaces, so helmfile with it is empty.
Is it possible to have empty helmfile yaml, or at least yaml without any releases?
With just  emty yaml i'm getting 
```
specified selector did not match any releases in any helmfile
```

**Comment by mumoshu** [comment]
@pastukhov Hey! Your use-case makes a lot of sense. And the error occurs when you miss "any" release in any helmfile.

So, one possible work-around is using the `helmfile.d/` feature or the `helmfiles:` config in helmfile.yaml to run multiple helmfile.yaml at once.

For example, you can create `helmfile.d/00-namespace.yaml` and `helmfile.d/01-apps.yaml`, run `helmfile -f helmfile.d/ sync` so that it deploys the namespace and then your apps because files in the directory is proccessed in the alphabetical order.

**Comment by mumoshu** [comment]
@pastukhov After #294, the error message is now `err: no releases found that matches specified selector() and environment(prod), in any helmfile`. That is, `helmfile` requires at least one of all the targeted yaml files to have the specified environment defined, while requiring at least one release that matches the selector exists in any helmfile yaml files.

If we changed this behavior, you'd probably have no way to notice that you misspelled the env name or the selector.

So, my best bet is you use `helmfile.d` or `helmfiles:` feature to leverage multiple yaml files.

Does my answer make sense?
Please inform me more about your use-case if it doesn't work, and/or you still want the requested feature! Thanks.

**Comment by pastukhov** [comment]
I will discuss it with our team, thanks

**Comment by pastukhov** [comment]
So, we made a hack in our CD scripts
```
if [ -s $(INVENTORY_DIR)/helm/namespaces.yaml ]; then
```
I close this issue now.
