### ISSUE TITLE
Setting concurrency = 1 breaks helmfile template with --set

### ISSUE THREAD

**Issue by Stono** [roboll/helmfile#288]
Using a concurrency of 1 breaks helmfile template because the arguments are set on `helm` on the first thread, the second thread then does a `helm fetch --set`, which results in `--set is an invalid argument`.

PR to fix this incoming...

**Comment by Stono** [comment]
@mumoshu would be great to get this merged and released ASAP as i've changed the interface for helm template slightly (no --concurrency), so minimising the impact of this breaking change.

**Comment by mumoshu** [comment]
Makes sense. In the future, it would be nice to have concurrency option for the helm-fetch part of lint and template commands though.

Thanks a lot for the fix anyway!

**Comment by Stono** [comment]
Yup I agree and I'm working on that, just wanted to prevent this issue in
the interim.

Do you think it should be configurable or we just do them all concurrently
regardless?  I can't really see anyone wanting to control it

**Comment by mumoshu** [comment]
I'd hope that it is configurable. Sequential download is always slow, and may harm u/x for serious users who is managing several dozens of releases with helmfile 😄Plus concurrently downloading dozens of charts doesn't seem to make sense either. Perhaps @sstarcher and @osterman would have more opinions, because they seem to manage many releases with helmfile?

But I completely agree with your YAGNI point. So, my stance is welcome any contribution about making  its concurrency configurable!

**Comment by sstarcher** [comment]
I have never used the lint or template commands of helmfile since they have been added.

On 26 releases
```
helmfile lint  17.25s user 6.87s system 198% cpu 12.165 total```

```
helmfile lint --concurrency=1  16.73s user 6.64s system 78% cpu 29.764 total
```

In my one off example looks like the command takes a little over 2x as long.

**Comment by Stono** [comment]
@sstarcher - I've just raised https://github.com/roboll/helmfile/pull/292 which parallelises those releases.
