### ISSUE TITLE
Go template "exec" function calls programs relative to current working directory

### ISSUE THREAD

**Issue by elemental-lf** [roboll/helmfile#299]
First of all: Thanks for helmfile and your fast and very user oriented development style. It is becoming more useful with every day. Your work is appreciated!

From my tests it seems that the new "exec" function calls programs relative to the current working directory which is different for example to the way value files (normal and *.gotmpl) are included or "readFile" works. I'd like to suggest two possible other options:
1. Call the program relative to the helmfile the Go template was included from
2. Call the program relative to the Go template
As "readFile" already uses the first option, "exec" should probably follow.

I'm using 0.33.0.

**Comment by mumoshu** [comment]
@elemental-lf Good point!

For consistency, I'd prefer the first option as you've commented.

But the benefit of the second option is that it provides extra reusability because it allows us to refer the same value templates file from within multiple helmfiles in different directories.

Do you mind if I changed the behavior of `readFile` along with `exec`, to that of the second option?

**Comment by elemental-lf** [comment]
@mumoshu, please go ahead, I think it's a good idea to go with the second option!

**Comment by elemental-lf** [comment]
@mumoshu Thank you very much!
