### ISSUE TITLE
environment when value is missing

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#317]
Say I have a environment values file specified with

```
value: blah
```

If I do `{{ .Environment.Values.missing }}` the output will be `< no value >`

Should we instead error out if the value is missing?

**Comment by mumoshu** [comment]
@sstarcher Good catch!

Just took some time for this, and got to know that the current behavior is [equivalent to that of helm templates](https://github.com/helm/helm/blob/3f0c6c54049d38e5c86dad1e9475f7dbf783be21/pkg/engine/engine.go#L231). You'll notice an helm template engine with `Strict: true` will use `missingkey=error` instead, but [such engine doesn't actually exist](https://github.com/helm/helm/blob/b95eb54bf27a3c7f7fee038536b728d21a817ccc/pkg/tiller/environment/environment.go#L215-L219).

Back to the original question, I find pros and cons for both options. The current behavior would be better for consistency with helm. But making it fail on any missing key is better to write solid templates.

I slightly prefer the current behavior, because it allows us to write:

```
{{ .Environment.Values.foo | default "FOO" }}
```

```
{{ if .Environment.Values.foo }}
{{ .Environment.Values.foo }}
{{ end }}
```

AFAIK, both templates fail when `missingkey=error`.

**Comment by sstarcher** [comment]
I can only speak to my use case, but I currently have no situation would I would ever want a use to write `{{ .Environment.Values.foo }}` and it evaluate to `no value` as that's essentially a unhandled error.

I don't know if it's possible in go template would, but my preference would be.

`{{ .Environment.Values.foo }}` - Would throw an error
`{{ .Environment.Values.foo | default "blah" }}` - Would result in blah

Less preferred, but workable would be 
`{{ .Environment.Values.foo | required }}` - which would throw a error.

So far in my situation converting everything over to templates I have not ran into a single instance where a null value is acceptable.  In each situation it would be a uncaught error.  Normally a user forgetting to supply a password for the environment.  Which is why I would prefer to not have to tell users everywhere they use environment variables that they need to catch for an error.

If the first 2 items are not feasible we could implement a second option of `{{ .Environment.Required.foo }}` or some such other value that requires it to exist.

**Comment by mumoshu** [comment]
@sstarcher Thanks for the comment!

> `{{ .Environment.Values.foo }}` - Would throw an error

This is possible just by setting `missingkey=error`.

> `{{ .Environment.Values.foo | default "blah" }}` - Would result in blah

`missingkey=error` breaks this. Your template fails at `.Environment.Values.foo`.

> `{{ .Environment.Values.foo | required }}` - which would throw a error.

This is possible. I guess this is how helmfile as of today works?

> If the first 2 items are not feasible we could implement a second option of `{{ .Environment.Required.foo }}` or some such other value that requires it to exist.

I wish we could! AFAIK, all we can do is either enable strict checks by setting `missingkey=error` or not. So, we can't just enable it partly by implementing a new template func/variable.

Do you have any good ides how we could implement it? I basically like strict checking as you've suggested, but it is just that I don't know how I can actually achieve it with golang text/template.

**Comment by sstarcher** [comment]
If it's not possible I would certainly lean toward missingkey=error.  And recommend people put their defaults in a values.yaml instead of using `| default "blah"`

**Comment by mumoshu** [comment]
@sstarcher Sounds good 👍 Thanks for the feedback. I'll take a look.

**Comment by sstarcher** [comment]
#308 resolves this
