### ISSUE TITLE
feat: Global hooks

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#331]
#295 is about hooking into the life cycle of each release in helmfile.yaml. #325 is about making the per-release hook reusable across releases.

In contract, the purpose of this feature is hooking into the life cycles of the helmfile command and each helmfile.yaml. So let's say you wanted to run some command before each helmfile run, a `onHelmfileStar` hook would make sense.

I don't have specific use-case(s) requires this feature, but as this concept has been seen in a few times in this project, I'd like to use this issue for aggregating more like that.

Relevant issues and comments:

- https://github.com/roboll/helmfile/issues/295#issuecomment-419859615

**Comment by simbo1905** [comment]
I am currently running my own scripts that do a "[pre-](https://github.com/ocd-scm/ocd-environment-webhook/blob/3d7c9f3ec5c199b58143169c339149b8365e0a2f/bin/ocd-environment.sh#L31)" and "[post-](https://github.com/ocd-scm/ocd-environment-webhook/blob/3d7c9f3ec5c199b58143169c339149b8365e0a2f/bin/ocd-environment.sh#L39)" `helm apply` which you can see at those links. 

I would like to use [glob patterns](https://github.com/roboll/helmfile/blob/413ab4f55b9091f29a7182fe6738ed2649955916/README.md#glob-patterns) so that an simply run a bunch of helmfiles within subfolders without my own custom script. I cannot do that until there are some lifecycle hooks mentioned in this ticket where I can run my pre- and post- helm apply scripts. 

The two use cases I currently have for these hooks are:

1. running our own secret decryption tooling 
2. managing tags within an openshift container registry

**Comment by simbo1905** [comment]
another use case that just popped up is to have a "post helmfile hook" script that sends out a notification that a particular microservice has been updated (e.g., post an message into a slack channel)

**Comment by davidecg** [comment]
We have to run a couple of commands to authenticate to aws and set the kubeconfig; this global hook would be perfect for that.

**Comment by simbo1905** [comment]
Now we have a helmfile that releases many secrets (shared by many apps) and we have to run a post script to ensure apps pick up the changes after all the secrets are refreshed. 

At the moment we always wrap running helmfile in a script that looks for `pre-` and `post-` global hooks.

**Comment by simbo1905** [comment]
we have moved half our apps onto helmfile in production. we use a subfolder per application with a separate helmfile. we run pre- and post- helmfile hooks. we also run a post everything hook

these do things like check for whether any secrets have changed requiring us to bounce deployments. they also do chatroom announcements. to tells us the status of deployments when we have changed or environments config repos and we are running helmfile apply across the whole repo to sync any changes. 

currently we have to use a custom script for this as helmfile doesn't have the hooks we need as per this ticket. we run these hooks starting at this [line](https://github.com/ocd-scm/ocd-environment-webhook/blob/184bdf9ec61d44258694153d4d3824cbce4bbd77/bin/ocd-environment.sh#L36) which is quite a lot of boilerplate code. we would rather simply everthing by using helmfile.d and define additional hooks, ones that run before and after each helmfile, and ones that run before and after starting to process the folder. 

if we got more hooks we could remove our boiler plate script that allows us to manage multiple apps in multiple environments all driven by git webhooks and helmfile.
