### ISSUE TITLE
[Question] Tons of helmfile overhead

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#335]
Due to a desire to better use githubs https://help.github.com/articles/about-codeowners/ so my team does not get spammed  with each configuration request I would like to separate our helmfiles by team.

This would result in around a dozen helmfiles.  The largest pain I see for this would be a call to `helmfile repos` or anything that calls a repo update like sync.  This would cause the repos to be synced a dozen times.

I can move my repo definition to the root helmfile which would allow me to ensure the repos exist, but each helmfile will still call repos to update the repos.

**Comment by mumoshu** [comment]
@sstarcher cukerman Ah, good point! Would it make sense to aggregate all the repos from all the helmfile.yaml, and run `helm repo update REPO` only when it is the first time against the REPO within a helmfile run?

**Comment by sstarcher** [comment]
That would be a great feature that I believe should resolve this issue for the repos.

**Comment by mumoshu** [comment]
It turned out that `helm repo update` doesn't accept a repository name to limit update to one.
So, I'm implementing a best-effort strategy to achieve the desired behavior. That is, helmfile mark which repository was updated, and skip second and further `helm repo update` when all the `repositories` found in a helmfile.yaml was marked as already updated.

Let's say you had two helmfiles, the first one with repositories `foo` and `bar`, an the second one with only `bar`. `helmfile repos` will run `helm update repo` for the first helmfile, marking `foo` and `bar` as already updated. The second helmfile.yaml contains only `bar`, which is marked as already updated. So helmfile won't run `helm repo update` for the second.

**Comment by mumoshu** [comment]
@sstarcher PTAL at #356

**Comment by sstarcher** [comment]
@mumoshu as always thank you

**Comment by mumoshu** [comment]
@sstarcher You're welcome. Thanks for your continuous supports! Hope I didn't break anything this time :)
