### ISSUE TITLE
feat: non-helm deployments

### ISSUE THREAD

**Issue by astorath** [roboll/helmfile#381]
Hi, we are trying to use helmfile as declarative configuration for our kubernetes clusters. But it can only manage helm deployments, which is not enough to manage all kube related tasks.

Consider the following:
1. Add support for `helm init` in helmfile. 
    Unfortunately helm has no (official) way to make a declarative installation of tiller on kube cluster, which can have a lot of options, not just run command and you're done.
2. Add support for `kubectl apply` for remote files. 
    Some artifacts are to be installed on cluster before tiller, like network plugins. This usually means running kubectl apply with some predefined remote file.
3. Add support for `kubectl delete`.
    Neither `kubectl apply` nor `helm install` has an option to destroy some predefined resources, which might be a part of cluster state. We do delete default and kube-public namespaces for instance.

PS: I know, this might be out of scope of helmfile itself, so I'm interested in your opinion on this.

**Comment by mumoshu** [comment]
@astorath Hey!

There seem to be no much momentum in this project to support the use-case yet.
But I'm personally aware of it!

For 1, the easiest way would be to use [helm-tiller](https://github.com/rimusz/helm-tiller). So that you don't need to run tiller beforehand and your helmfile command looks like `helm tiller run -- helmfile ...`. 
 Actually, I've contributed the `helm tiller run` command myself, for this use-case.

No out-of-box support for `helm init` would also be good in regard to that helm v3 gets rid of tiller.

For 2, although it doesn't exactly match what you've requested, could try a kind of "helmify" command plus helmfile's "hook" feature? The [helmfile + kustomize example](https://github.com/roboll/helmfile#helmfile--kustomize) in our README would be a good source of inspiration.

I have no idea how No. 3 fits within the scope of helmfile yet. The next best thing helmfile could provide would be a `onHelmfileStart` hook #331. With that, you would write a custom script that discovers and then removes predefined resources.

**Comment by astorath** [comment]
@mumoshu 

Do you plan on integrating helmfile with helm tiller plugin? This would be helpful in CI environment.

**Comment by mumoshu** [comment]
Hey! Would you mind opening a dedicated issue for that?
I personally love the integration, but just missed writing an issue for
discussions.
2019年1月23日(水) 0:04 astorath <notifications@github.com>:

**Comment by astorath** [comment]
done
