### ISSUE TITLE
Helmfile should run `dependency build` and not `update`

### ISSUE THREAD

**Issue by victornoel** [roboll/helmfile#415]
I think that `helm dependency update` is meant to be used to explicitly update the lockfile, while `helm dependency build` is meant to be used to get your `charts` directory in a state coherent with the requirements lock file.

Since `sync` and `apply` are meant to be used to update real clusters, I believe that it is a bad idea to update the lockfile since it exists exactly for the purpose of locking dependencies.

**Comment by mumoshu** [comment]
@sstarcher @victornoel Could you give me some feedback?

After looking into #410, I'm considering to change helmfile to run `helm dependency build`(not update) as a part of `helmfile diff`.

I remember that I had chosen not to run `helm dependency update` as a part of `helmfile diff` so that the user can control when to do so. But it introduced an [another issue](https://github.com/roboll/helmfile/issues/410#issuecomment-445480869).

@sstarcher Do you currently version-control not only `requirements.yaml`, but `requirements.lock` as well for your remote/local charts? If not, after the change, you'd  be encouraged to do so.

How does that sounds to you two?

**Comment by victornoel** [comment]
@mumoshu I think dependency build should be run everytime to be consistent between the various diff, apply and sync commands.

Maybe something that can also be added is an `helmfile dependency build` (as well as update?) command to run `helm dependency build` for all defined releases.

**Comment by mumoshu** [comment]
@victornoel Thanks for the confirmation! Yes, I think running `helmfile dependency build` in any helmfile command that works with the chart including `diff`, `sync`, `apply`, and `template` would make sense.

I had considered `helmfile dependency build` but had no specific use-cases for itmyself. Do you have any? As long as helmfile automatically runs `helm dependency build` when necessary, there would be no need to manually run it.

However, `helmfile dependency update` would be useful to update all the requirements.lock in all the releases managed by helmfile.

**Comment by victornoel** [comment]
> I had considered helmfile dependency build but had no specific use-cases for itmyself. Do you have any? As long as helmfile automatically runs helm dependency build when necessary, there would be no need to manually run it.

Yes of course

> However, helmfile dependency update would be useful to update all the requirements.lock in all the releases managed by helmfile.

I agree :)

**Comment by mumoshu** [comment]
@victornoel Thanks! Opened #450 for `dependency update`.

**Comment by sstarcher** [comment]
@mumoshu I don't use file based pathing to charts.  All of our charts are released to a helm chart repo.  We do include the lockfile in the github repo as that's generally considered best practice to lock your dependencies.

**Comment by victornoel** [comment]
@mumoshu solution is great, thanks :)
