### ISSUE TITLE
helmfile delete shoud use --purge as default

### ISSUE THREAD

**Issue by sgandon** [roboll/helmfile#511]
I never understood why you would not want to purge everything upon delete.
it seems that is may be used for troubleshooting but if you want to delete a release why would you want to troubleshoot anything.
The problem is that when you forget the `--purge` in the "helmfile delete" command you are getting into trouble when you want to install resources again. 

So I would suggest that the default delete behaviour was `--purge` and that is someone wants to *not* purge the release he/she should add an explicit flag on the commandline. That would save many trouble.

**Comment by mumoshu** [comment]
Practically speaking, I agree with you 👍 I've never encountered circumstances that `--purge` was unnecessary.

**Comment by mumoshu** [comment]
A bit of history is:

- #33 resulted in the addition of `--purge` made in #34. I thought `--purge` was the default behavior in the beginning
- #71 resulted in #142 which made `--purge` optional. The rationale was the consistency with `helm delete`

**Comment by mumoshu** [comment]
Can we add `helmfile destroy`(`--purge` by default) AND deprecate `helmfile delete`? WDYT? @sgandon @cmeury @sstarcher @osterman 

The context: I now remember that I was considering to add `helmfile destroy` which is basically `helmfile delete --purge` so that we don't confuse helm users, as discussed in https://github.com/roboll/helmfile/issues/71#issuecomment-379218977. Just adding `helmfile destroy` while keeping `helmfile delete` will also confuse users, though.

**Comment by sgandon** [comment]
I am very fine with your proposal of using `destroy` to have the purge by default.

**Comment by cmeury** [comment]
Fine with me. I never use `helmfile delete` alone.

**Comment by mumoshu** [comment]
Thanks everyone. `helmfile destroy` has been implemented in v0.53.0.
