### ISSUE TITLE
Note about production users

### ISSUE THREAD

**Issue by mumoshu** [roboll/helmfile#52]
Similar to [the one for kubernetes-on-aws](https://github.com/hjacobs/kubernetes-on-aws-users).

It will help users and maintainers have another aspect of confidence in their project and tooling, while allowing maintainers to try to contact prod users in case it seems necessary(like before making a breaking change, scope-creep, etc.

**Comment by roboll** [comment]
I’m fine with this if people want to volunteer their info, but I’m not sure if there are other implications. 

There should certainly be no sponsorship or anything like that, no money changing hands.

**Comment by mumoshu** [comment]
> no money changing hands

I have never heard of this great word! Yes, that's definitely what I expect for a healthy OSS object 👍

**Comment by cmeury** [comment]
Information from my side, which can be used if anyone is in the mood for a PR.

* **Link:** https://www.ricardo.ch/
* **Description:** ricardo.ch is the largest online marketplace in Switzerland - the well-known service provides customers the best possible e-commerce experience since 1999.
* **Logo:** https://style-6a38.kxcdn.com/12.2.4/lib/images/ric-logo__core.svg

**Comment by cmeury** [comment]
@mumoshu This one can possibly be closed.

**Comment by mumoshu** [comment]
@cmeury Yes. Thanks for reminding me 👍
