### ISSUE TITLE
helmfile lint checks comments

### ISSUE THREAD

**Issue by phumberdroz** [roboll/helmfile#607]
Hey,

helmfile version v0.63.0

`helmfile lint` checks comments

example file:
https://gist.github.com/phumberdroz/dc14444479a5d46e7204d186898b4227#file-helmfile-yaml-L32

Error:
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:32:25: executing "stringTemplate" at <requiredEnv "DB_USERNAME">: error calling requiredEnv: required env var `DB_USERNAME` is not set

**Comment by mumoshu** [comment]
Hey @phumberdroz!

This is unavoidable, because your whole helmlfile.yaml is a go template, that MUST Be firstly rendered in order to be linted as a YAML document. No matter where go template expression it appears it is rendered, because it is a go template anyway.

So, If you don't want it to be rendered, defer it by using Release Template #439, like:
```
{{` {{ whatever }} `}}
```

Otherwise just remove the offending comments inf unneeded.

**Comment by phumberdroz** [comment]
Thanks for explaining. 

It is just the example stuff I wanted to keep in when I started exploring helmfile and saw that it basically does not work.

As this is intended behavior I will close this issue
