### ISSUE TITLE
Make purge optional when running "helmfile delete"

### ISSUE THREAD

**Issue by cmeury** [roboll/helmfile#71]
Currently, `helmfile delete` runs `helm delete --purge`. This might be unexpected for helm users. Shouldn't purge be an optional flag?

Alternatively, we could have two actual commands for convenience and to make it crystal clear:

    helmfile delete
    helmfile purge

**Comment by mumoshu** [comment]
@cmeury Thanks for the feedback!

Would you mind helping me to understand the use-case here?

Basically, `helm delete` without `--purge` only makes sense to me when you're auto-naming releases, because then you don't normally need to purge them.

However, `helmfile` enforces specific names to the releases. If `helmfile delete` enforce `--purge` by default, I can't just run `helmfile delete && helmfile sync` which is rather confusing to me.
So, back to my question, what's the use-case of leaving named releases on `helmfile delete` by default?

**Comment by cmeury** [comment]
The reason is is two-fold: Firstly, I would expect `helmfile` to behave similar to `helm`, where deleting does not also purge automatically. It might surprise users who are already familiar with Helm. Secondly, purging [removes all release history](https://github.com/kubernetes/helm/issues/1395#issuecomment-254608944), which, while certainly convenient, does not make it a good default behavior.

But since I know how convenient the current behaviour is, I was suggesting adding an actual top-level `purge`action instead of as an argument to `delete`. So, instead of `helmfile delete && helmfile sync`, you would just run `helmfile purge && helmfile sync`.

But I totally understand if you're not convinced by this, no hard feelings :)

**Comment by mumoshu** [comment]
@cmeury First of all, thanks for very informative response and the feedback as always!

I do believe that I understand the friendliness of `helmfile purge` for experienced helm users.
On the other hand, I don't want to replicate (potentially) all the helm sub-commands to helmfile, especially when the job was just running helm sub-command for each release.

So, how about renaming `helmfile delete` to something else, doesn't conflict with `helm delete` so that helm users won't confuse it with regular helm sub-command's semantic? Probably `helmfile destroy` so that helmfile's basic use-case involves `helmfile sync` and `helmfile destroy`. `helmfile up` vs `helmfile down` also sounds sweet to me.

Anyway, a deprecation warning for `helmfile delete` would be necessary in order to make existing helmfile users happy!

**Comment by mumoshu** [comment]
@cmeury I understand there are use-cases that you'd want to just run a specific helm sub-command for each release helmfile manages, in general.

For that, how about adding e.g. `helmfile status -o json` on top of #27  so that you could do e.g.

```console
helmfile status -o json | jq '.[].name' | xargs -n 1 helm delete --purge
```

to run arbitrary helm sub-command for each release in oneshot.
Yes, I love unix philosophy ☺️

**Comment by cmeury** [comment]
> how about renaming `helmfile delete` to [..] `helmfile destroy` so that helmfile's basic use-case involves `helmfile sync` and `helmfile destroy`.

This sounds very reasonable. Maybe a third contributor could weigh in here to reach a certain quorum. And yes, deprecation warning makes sense.

> For that, how about adding e.g. `helmfile status -o json` on top of #27 ..

I am not quite sure why I would do that if we can just:

    helmfile destroy -l name=foobar

But now that I think about it, maybe we need to be able to select not only on labels but on status? Then it might actually work like this:

    helmfile destroy --failed

**Comment by mumoshu** [comment]
Ah, `helmfile destroy -l name=foobar` would definitely work! My example wasn't good at all.

My sentiment was that we don't necessarily want to implement every possible options and flags to helmfile for purpose of supporting all the possible use-cases which can be achieved elegantly conforming the unix philosophy.

More concretely, we don't have ways to scrape rendered release names from helmfile.yml currently so it is hard to combine helmfile with external tools. Something like `helmfile status -o json` would allow us to combine external tools via pipes, anyway.

**Comment by mumoshu** [comment]
@cmeury I re-read your [proposal in the middle of this thread](https://github.com/roboll/helmfile/issues/71#issuecomment-376690779) and reconsidered several times. I now realize `helmfile purge`(reflects `helm delete --purge` hence more friendly to helm users) or even `helmfile delete --purge` sounds better to me than `helmfile destroy`.

So, I'd rather do:

- Revert #34 
- Add `--purge` option to `helmfile delete`
- Note about the common idiom of running `helmfile delete --purge && helmfile sync` to force reinstalling everything.

**Comment by mumoshu** [comment]
Submitted #142 for this
