### ISSUE TITLE
bug: HelmState.scatterGather ignores item parameter

### ISSUE THREAD

**Issue by travisgroth** [roboll/helmfile#793]
Came across this in #782 

See https://github.com/roboll/helmfile/blob/bce2f4728b71a7a173766f11e1018c200e4c602c/pkg/state/state_run.go#L15-L20

It looks like the intention was to make that method generic and be informed of the number of items coming in, but it seems to default/max against the number of releases instead.

This may be the first/only non-release based usage.  It would be good to re-use it for environment secrets.  

My proposal is to use the items parameter, which is currently unused.  Can put in a PR if that makes sense.

**Comment by mumoshu** [comment]
@travisgroth Wow! Good catch.

Yeah `items` should be used instead of `len(st.Releases)` when concurrency isn't specified(0).

To be extra clear, I believe it should be:

```
 if concurrency < 1 { 
 	concurrency = items 
 } else if concurrency > items { 
 	concurrency = items 
 } 
```

Or even just:

```
 if concurrency < 1 || concurrency > items { 
 	concurrency = items 
 }
```

Btw `concurrency > items` is there to cap concurrency to number of items. This isn't strictly needed, but for avoiding unnecessary/redundant goroutines.

I'd appreciate it if you could submit a PR 😄
