### ISSUE TITLE
Should postsync hook only run if sync was successful?

### ISSUE THREAD

**Issue by jradtilbrook** [roboll/helmfile#826]
The current implementation of the postsync hook is only semantically different to cleanup but they are run one after the other with the same parameters.

I would expect postsync to only run if the sync was successful (which I did assume until looking into the code) otherwise I don't understand why having 2 events that run sequentially with no different parameters is necessary. Or perhaps adding the success/failure status of the release to the context so it can be used in the templating of the command that gets run.

I'm happy to make a PR if this logic sounds correct, otherwise any reasoning or workaround I could use to determine if the sync was successful would be greatly appreciated.

**Comment by mumoshu** [comment]
@jradtilbrook Hey! It's intentional, but I'm open to suggestions. Anyways, please let me how it's designed and intended to work.

`prepare` is intended for modifying the local chart or setting up the local env while `clean` is for cleaning up the modification. `prepare` and `clean` are run on every helmfile command.

In contrast, `presync` and `postsync` are run on helmfile sync/apply. `postsync` is run so that you can correctly clean up e.g. `kubectl delete` the resources created on `presync` regardless of the success/failure status.

Does this make sense? Is it just frustrating for you, or making configuration difficult or impossible? I'd appreciate any feedback. Thanks!

**Comment by jradtilbrook** [comment]
Hey @mumoshu thanks for getting back to me. That explanation clears up how it's intended to work. I was making incorrect assumptions to try fit it into my usecase.

For me, I want to perform some action after the manifests have been synced to the cluster but only if it was successful (ie. if the containers reached a running state within the wait timeout). I can think of two ways to do this but both mean introducing extra functionality so let me know if you are okay with that:

1. Adding another event such as `syncsuccess` which is only triggered when helm can apply the chart.
2. Adding an extra parameter to the template for `postsync` that holds the boolean value of whether the sync was successful.

I can then use either of those events knowing that the sync was successful and performing the action I want to do.

**Comment by mumoshu** [comment]
@jradtilbrook Thankns! Your use-case makes sense to me.

Probably the option 2 is better, as in the option 1 I have no good answer to whether to allow both `postsync` and `syncsuccess` and/or their ordering(should `syncsuccess` run after `postsync`, or vice versa, or  make only one of them configurable at a time, etc?)

**Comment by jradtilbrook** [comment]
Sorry it took so long to reply, I've been quite busy. Okay great, that is my preference as well and I think it should only be a few lines of code. I'm looking at it today and hope to provide a PR very soon
